name: Bump version

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses:  phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: 'Bumps version to {{version}}'
