name: Deploy

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build:
    name: Build and deploy
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
      - uses: 'rimonhanna/gh-action-bump-version@master'
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "guru-shop"
          heroku_email: "tomaszjarkowski1998@gmail.com"